import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Same jade used throughout the app's light-mode palette — chosen over the
// dark-mode jade since PDFs are read on a white page, not a dark UI.
const BRAND_JADE: [number, number, number] = [31, 142, 107];
const MUTED_GRAY: [number, number, number] = [110, 118, 128];
const INK: [number, number, number] = [20, 22, 24];

const MARGIN = 40;

export function createPdfDoc(): jsPDF {
  return new jsPDF({ unit: "pt", format: "a4" });
}

/** Branded header bar with the app name, document title, and a subtitle
 * (typically the month/date range this export covers). Returns the y
 * position content should start below. */
export function addHeader(doc: jsPDF, title: string, subtitle: string): number {
  const width = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND_JADE);
  doc.rect(0, 0, width, 72, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Coffer", MARGIN, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.text(title, MARGIN, 48);

  doc.setFontSize(9);
  doc.text(subtitle, MARGIN, 62);

  doc.setTextColor(...INK);
  return 96;
}

export function addSectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...INK);
  doc.text(text, MARGIN, y);
  doc.setFont("helvetica", "normal");
  return y + 14;
}

type AutoTableResult = { lastAutoTable: { finalY: number } };

/** A plain label/value list — for a handful of standalone figures rather
 * than a proper multi-row, multi-column table. */
export function addKeyValueRows(doc: jsPDF, rows: [string, string][], startY: number): number {
  autoTable(doc, {
    startY,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { textColor: MUTED_GRAY },
      1: { halign: "right", fontStyle: "bold", textColor: INK },
    },
    body: rows,
    margin: { left: MARGIN, right: MARGIN },
  });
  return (doc as unknown as AutoTableResult).lastAutoTable.finalY + 18;
}

export function addTable(doc: jsPDF, head: string[], body: string[][], startY: number): number {
  autoTable(doc, {
    startY,
    head: [head],
    body,
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: BRAND_JADE, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [246, 247, 246] },
    margin: { left: MARGIN, right: MARGIN },
  });
  return (doc as unknown as AutoTableResult).lastAutoTable.finalY + 18;
}

/** Adds a "generated on / page X of Y" footer to every page, then triggers
 * the actual browser download. Must only ever be called from a click
 * handler — it's the one part of this file that touches browser-only APIs. */
export function addFooterAndSave(doc: jsPDF, filename: string): void {
  const pageCount = doc.getNumberOfPages();
  const generatedOn = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_GRAY);
    doc.text(
      `Generated by Coffer on ${generatedOn} — Page ${i} of ${pageCount}`,
      MARGIN,
      doc.internal.pageSize.getHeight() - 20
    );
  }

  doc.save(filename);
}

/** Turns a page title into a safe, readable filename fragment. */
export function slugifyForFilename(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
